import type { Ingredient } from "@/content/schema";

/**
 * Ingredient master list (docs/04 §2, docs/05 §2). Built BEFORE recipes — every
 * RecipeIngredient.ingredientId must resolve here. Prices are German 2026
 * estimates calibrated to the anchors in docs/05 §1 (Standard-Supermarkt for
 * normal items, Asia-Laden/online for specialty). IDs are stable forever.
 *
 * Rule (validator): every `japanische-basics` item and every `asiaLadenHint`
 * item carries a resolving `lexiconId`.
 */

type IngredientDraft = Omit<
  Ingredient,
  "asiaLadenHint" | "isStaple" | "perishable" | "substitutes"
> &
  Partial<
    Pick<
      Ingredient,
      "asiaLadenHint" | "isStaple" | "perishable" | "substitutes"
    >
  >;

/** Fill the flag/array defaults so entries stay terse but data stays explicit. */
const mk = (d: IngredientDraft): Ingredient => ({
  asiaLadenHint: false,
  isStaple: false,
  perishable: false,
  substitutes: [],
  ...d,
});

export const ingredients: Ingredient[] = [
  /* ----------------------- Japanische Basics ----------------------- */
  mk({
    id: "shoyu",
    name: "Sojasauce (Shoyu)",
    emoji: "🍶",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "shoyu",
    price: {
      amount: 100,
      unit: "ml",
      eur: 0.7,
      packEur: 3.5,
      packNote: "500-ml-Flasche",
    },
  }),
  mk({
    id: "mirin",
    name: "Mirin",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "mirin",
    price: {
      amount: 100,
      unit: "ml",
      eur: 1.0,
      packEur: 4.0,
      packNote: "400-ml-Flasche",
    },
    substitutes: [
      {
        text: "1 EL Zucker in 2 EL Weißwein oder Wasser auflösen",
        quality: "okay",
      },
      {
        ingredientId: "reisessig",
        text: "Reisessig + Prise Zucker (nur zur Not)",
        quality: "notloesung",
      },
    ],
  }),
  mk({
    id: "kochsake",
    name: "Sake zum Kochen",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "sake",
    price: {
      amount: 100,
      unit: "ml",
      eur: 0.8,
      packEur: 4.0,
      packNote: "500-ml-Flasche",
    },
    substitutes: [
      { text: "Trockener Weißwein", quality: "gleichwertig" },
      { text: "Weglassen und 1 EL Wasser mehr nehmen", quality: "okay" },
    ],
  }),
  mk({
    id: "miso-hell",
    name: "Helles Miso (Shiro)",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "miso",
    price: {
      amount: 100,
      unit: "g",
      eur: 1.0,
      packEur: 5.0,
      packNote: "500-g-Becher",
    },
    substitutes: [
      {
        ingredientId: "miso-rot",
        text: "Rotes Miso, kräftiger — etwas weniger nehmen",
        quality: "okay",
      },
    ],
  }),
  mk({
    id: "miso-rot",
    name: "Rotes Miso (Aka)",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "miso",
    price: {
      amount: 100,
      unit: "g",
      eur: 1.0,
      packEur: 5.0,
      packNote: "500-g-Becher",
    },
    substitutes: [
      {
        ingredientId: "miso-hell",
        text: "Helles Miso, milder — etwas mehr nehmen",
        quality: "okay",
      },
    ],
  }),
  mk({
    id: "dashi-pulver",
    name: "Dashi-Pulver (Bonito)",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "dashi",
    price: {
      amount: 100,
      unit: "g",
      eur: 3.5,
      packEur: 4.0,
      packNote: "kleine Tüte, reicht ewig",
    },
    substitutes: [
      { text: "Kombu + Katsuobushi selbst auskochen", quality: "gleichwertig" },
    ],
  }),
  mk({
    id: "dashi-pulver-vegan",
    name: "Vegane Dashi (Kombu)",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "dashi",
    price: {
      amount: 100,
      unit: "g",
      eur: 4.0,
      packEur: 5.0,
      packNote: "kleine Tüte",
    },
    substitutes: [
      {
        ingredientId: "kombu",
        text: "Kombu 15 Min in heißem Wasser ziehen lassen",
        quality: "gleichwertig",
      },
    ],
  }),
  mk({
    id: "kombu",
    name: "Kombu (Alge)",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "kombu",
    price: {
      amount: 100,
      unit: "g",
      eur: 4.0,
      packEur: 6.0,
      packNote: "getrocknet, hält ewig",
    },
  }),
  mk({
    id: "katsuobushi",
    name: "Katsuobushi (Bonitoflocken)",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "katsuobushi",
    price: {
      amount: 100,
      unit: "g",
      eur: 6.0,
      packEur: 4.0,
      packNote: "Tüte mit Flocken",
    },
  }),
  mk({
    id: "reisessig",
    name: "Reisessig",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "reisessig",
    price: {
      amount: 100,
      unit: "ml",
      eur: 0.8,
      packEur: 3.0,
      packNote: "500-ml-Flasche",
    },
    substitutes: [
      { text: "Milder Weißweinessig + Prise Zucker", quality: "okay" },
      { text: "Apfelessig", quality: "notloesung" },
    ],
  }),
  mk({
    id: "sesamoel",
    name: "Sesamöl (geröstet)",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "sesamoel",
    price: {
      amount: 100,
      unit: "ml",
      eur: 2.0,
      packEur: 5.0,
      packNote: "250-ml-Flasche",
    },
    substitutes: [
      {
        text: "Nur zur Not neutrales Öl + ein paar geröstete Sesamkörner",
        quality: "notloesung",
      },
    ],
  }),
  mk({
    id: "panko",
    name: "Panko (Paniermehl)",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "panko",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.8,
      packEur: 2.0,
      packNote: "200-g-Beutel",
    },
    substitutes: [
      { text: "Grobe Semmelbrösel (weniger knusprig)", quality: "okay" },
    ],
  }),
  mk({
    id: "nori",
    name: "Nori (Blätter)",
    namePlural: "Nori-Blätter",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "nori",
    price: {
      amount: 1,
      unit: "blatt",
      eur: 0.2,
      packEur: 3.0,
      packNote: "Packung mit ~10 Blättern",
    },
  }),
  mk({
    id: "wakame",
    name: "Wakame (getrocknet)",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "wakame",
    price: {
      amount: 100,
      unit: "g",
      eur: 5.0,
      packEur: 3.0,
      packNote: "50-g-Tüte, quillt stark",
    },
  }),
  mk({
    id: "furikake",
    name: "Furikake",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "furikake",
    price: {
      amount: 100,
      unit: "g",
      eur: 3.0,
      packEur: 3.0,
      packNote: "Streuer ~50 g",
    },
  }),
  mk({
    id: "kewpie-mayo",
    name: "Kewpie-Mayo",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "kewpie-mayo",
    price: {
      amount: 100,
      unit: "g",
      eur: 1.2,
      packEur: 4.0,
      packNote: "Quetschflasche ~300 g",
    },
    substitutes: [
      {
        text: "Normale Mayo + Prise Zucker + Schuss Reisessig",
        quality: "okay",
      },
    ],
  }),
  mk({
    id: "curry-roux",
    name: "Japanische Curry-Roux",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "curry-roux",
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.45,
      packEur: 3.5,
      packNote: "Block mit ~8 Würfeln",
    },
  }),
  mk({
    id: "gochujang",
    name: "Gochujang",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "gochujang",
    price: {
      amount: 100,
      unit: "g",
      eur: 1.2,
      packEur: 4.0,
      packNote: "500-g-Becher",
    },
    substitutes: [
      {
        ingredientId: "miso-rot",
        text: "Rotes Miso + Chili (weniger süß)",
        quality: "notloesung",
      },
    ],
  }),
  mk({
    id: "sriracha",
    name: "Sriracha",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "sriracha",
    price: {
      amount: 100,
      unit: "ml",
      eur: 0.9,
      packEur: 3.0,
      packNote: "Quetschflasche",
    },
  }),
  mk({
    id: "shichimi",
    name: "Shichimi Togarashi",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "shichimi",
    price: {
      amount: 100,
      unit: "g",
      eur: 4.0,
      packEur: 3.0,
      packNote: "kleiner Streuer",
    },
  }),
  mk({
    id: "tonkatsu-sauce",
    name: "Tonkatsu-Sauce",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "tonkatsu-sauce",
    price: {
      amount: 100,
      unit: "ml",
      eur: 1.2,
      packEur: 4.0,
      packNote: "Flasche ~300 ml",
    },
    substitutes: [
      { text: "Ketchup + Worcestersauce + Prise Zucker", quality: "okay" },
    ],
  }),
  mk({
    id: "okonomiyaki-sauce",
    name: "Okonomiyaki-Sauce",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "tonkatsu-sauce",
    price: {
      amount: 100,
      unit: "ml",
      eur: 1.2,
      packEur: 4.0,
      packNote: "Flasche ~300 ml",
    },
    substitutes: [
      {
        ingredientId: "tonkatsu-sauce",
        text: "Tonkatsu-Sauce (fast identisch)",
        quality: "gleichwertig",
      },
    ],
  }),
  mk({
    id: "doubanjiang",
    name: "Doubanjiang (Tobanjan)",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "doubanjiang",
    price: {
      amount: 100,
      unit: "g",
      eur: 1.5,
      packEur: 4.0,
      packNote: "Glas ~200 g",
    },
    substitutes: [
      {
        ingredientId: "gochujang",
        text: "Gochujang (süßer, weniger salzig)",
        quality: "okay",
      },
      {
        ingredientId: "miso-rot",
        text: "Rotes Miso + Chili",
        quality: "notloesung",
      },
    ],
  }),
  mk({
    id: "umeboshi",
    name: "Umeboshi (eingelegte Pflaume)",
    namePlural: "Umeboshi",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "umeboshi",
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.6,
      packEur: 5.0,
      packNote: "Glas mit ~10 Stück",
    },
  }),
  mk({
    id: "udon",
    name: "Udon-Nudeln (vorgekocht)",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "japanische-nudeln",
    price: {
      amount: 1,
      unit: "packung",
      eur: 0.85,
      packEur: 2.5,
      packNote: "3er-Pack, je ~200 g",
    },
    substitutes: [
      {
        ingredientId: "somen",
        text: "Andere dicke Weizennudeln",
        quality: "okay",
      },
    ],
  }),
  mk({
    id: "soba",
    name: "Soba-Nudeln",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "japanische-nudeln",
    price: {
      amount: 100,
      unit: "g",
      eur: 1.0,
      packEur: 3.0,
      packNote: "250-g-Packung, trocken",
    },
  }),
  mk({
    id: "somen",
    name: "Somen-Nudeln",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "japanische-nudeln",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.9,
      packEur: 2.5,
      packNote: "getrocknet",
    },
  }),
  mk({
    id: "ramen-instant",
    name: "Instant-Ramen (nur Nudeln)",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "japanische-nudeln",
    price: {
      amount: 1,
      unit: "packung",
      eur: 1.0,
      packEur: 1.2,
      packNote: "Packung ~100 g",
    },
    substitutes: [
      {
        text: "Jede Instant-Nudel — Würzpäckchen weglassen",
        quality: "gleichwertig",
      },
    ],
  }),
  mk({
    id: "yakisoba-nudeln",
    name: "Yakisoba-Nudeln (vorgekocht)",
    category: "japanische-basics",
    section: "asia-regal",
    lexiconId: "japanische-nudeln",
    price: {
      amount: 1,
      unit: "packung",
      eur: 0.85,
      packEur: 2.5,
      packNote: "3er-Pack, je ~150 g",
    },
    substitutes: [
      {
        ingredientId: "ramen-instant",
        text: "Instant-Ramen-Nudeln (ohne Würzpäckchen)",
        quality: "okay",
      },
    ],
  }),
  mk({
    id: "aburaage",
    name: "Aburaage (frittierte Tofutaschen)",
    namePlural: "Aburaage",
    category: "japanische-basics",
    section: "asia-regal",
    asiaLadenHint: true,
    lexiconId: "aburaage",
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.5,
      packEur: 2.5,
      packNote: "Packung ~5 Stück, gut einfrierbar",
    },
    substitutes: [
      {
        ingredientId: "tofu",
        text: "Fester Tofu in dünnen Scheiben, kurz angebraten",
        quality: "notloesung",
      },
    ],
  }),
  mk({
    id: "sushi-reis",
    name: "Sushi-Reis (Rundkorn)",
    category: "vorratsschrank",
    section: "asia-regal",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.4,
      packEur: 4.5,
      packNote: "1-kg-Beutel",
    },
    substitutes: [
      {
        ingredientId: "reis",
        text: "Milchreis/Risottoreis (klebt ähnlich)",
        quality: "okay",
      },
    ],
  }),

  /* --------------------------- Reis & Basis --------------------------- */
  mk({
    id: "reis",
    name: "Reis (Rundkorn)",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.3,
      packEur: 3.5,
      packNote: "1-kg-Beutel",
    },
  }),

  /* --------------------------- Frische: Ei/Tofu ----------------------- */
  mk({
    id: "ei",
    name: "Ei",
    namePlural: "Eier",
    emoji: "🥚",
    category: "frische-zutaten",
    section: "kuehlregal",
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.35,
      packEur: 2.5,
      packNote: "10er-Packung",
    },
  }),
  mk({
    id: "tofu",
    name: "Tofu (fest, natur)",
    category: "frische-zutaten",
    section: "kuehlregal",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.55,
      packEur: 2.2,
      packNote: "400-g-Packung",
    },
    substitutes: [
      {
        ingredientId: "tofu-seiden",
        text: "Seidentofu (weicher, zerfällt leichter)",
        quality: "okay",
      },
    ],
  }),
  mk({
    id: "tofu-seiden",
    name: "Seidentofu",
    category: "frische-zutaten",
    section: "kuehlregal",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.6,
      packEur: 2.4,
      packNote: "300–400-g-Packung",
    },
    substitutes: [
      {
        ingredientId: "tofu",
        text: "Fester Tofu (fester Biss)",
        quality: "okay",
      },
    ],
  }),

  /* --------------------------- Fleisch & Fisch ------------------------ */
  mk({
    id: "haehnchenschenkel",
    name: "Hähnchenschenkel (entbeint)",
    category: "frische-zutaten",
    section: "fleisch-fisch",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.9,
      packEur: 5.0,
      packNote: "ca. 500 g",
    },
    substitutes: [
      {
        ingredientId: "haehnchenbrust",
        text: "Hähnchenbrust (trockener, kürzer garen)",
        quality: "okay",
      },
    ],
  }),
  mk({
    id: "haehnchenbrust",
    name: "Hähnchenbrust",
    category: "frische-zutaten",
    section: "fleisch-fisch",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.95,
      packEur: 5.0,
      packNote: "ca. 2 Filets",
    },
    substitutes: [
      {
        ingredientId: "haehnchenschenkel",
        text: "Hähnchenschenkel (saftiger)",
        quality: "gleichwertig",
      },
    ],
  }),
  mk({
    id: "schweinebauch",
    name: "Schweinebauch (dünn geschnitten)",
    category: "frische-zutaten",
    section: "fleisch-fisch",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.9,
      packEur: 4.5,
      packNote: "ca. 500 g",
    },
  }),
  mk({
    id: "schweinenacken",
    name: "Schweinenacken (dünn geschnitten)",
    category: "frische-zutaten",
    section: "fleisch-fisch",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.85,
      packEur: 4.5,
      packNote: "ca. 500 g",
    },
  }),
  mk({
    id: "schweineschnitzel",
    name: "Schweineschnitzel (Lende)",
    namePlural: "Schweineschnitzel",
    category: "frische-zutaten",
    section: "fleisch-fisch",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.85,
      packEur: 5.0,
      packNote: "ca. 2 Schnitzel",
    },
  }),
  mk({
    id: "rindfleisch",
    name: "Rindfleisch (hauchdünn geschnitten)",
    category: "frische-zutaten",
    section: "fleisch-fisch",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 1.6,
      packEur: 8.0,
      packNote: "ca. 400 g",
    },
    substitutes: [
      {
        text: "Rinderhüfte 15 Min anfrieren, dann hauchdünn schneiden",
        quality: "gleichwertig",
      },
    ],
  }),
  mk({
    id: "hackfleisch",
    name: "Hackfleisch (gemischt)",
    category: "frische-zutaten",
    section: "fleisch-fisch",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.7,
      packEur: 3.5,
      packNote: "500-g-Packung",
    },
  }),
  mk({
    id: "hackfleisch-schwein",
    name: "Schweinehack",
    category: "frische-zutaten",
    section: "fleisch-fisch",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.75,
      packEur: 3.5,
      packNote: "500-g-Packung",
    },
    substitutes: [
      {
        ingredientId: "hackfleisch",
        text: "Gemischtes Hack",
        quality: "gleichwertig",
      },
    ],
  }),
  mk({
    id: "kochschinken",
    name: "Kochschinken",
    category: "frische-zutaten",
    section: "kuehlregal",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 1.2,
      packEur: 2.0,
      packNote: "150-g-Packung",
    },
  }),
  mk({
    id: "lachs",
    name: "Lachsfilet",
    category: "frische-zutaten",
    section: "fleisch-fisch",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 2.5,
      packEur: 6.0,
      packNote: "ca. 2 Filets",
    },
  }),
  mk({
    id: "thunfisch-dose",
    name: "Thunfisch (Dose)",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 1,
      unit: "dose",
      eur: 1.2,
      packEur: 1.2,
      packNote: "150-g-Dose (~100 g abgetropft)",
    },
  }),

  /* ------------------------------- Gemüse ----------------------------- */
  mk({
    id: "fruehlingszwiebel",
    name: "Frühlingszwiebel",
    namePlural: "Frühlingszwiebeln",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.2,
      packEur: 1.1,
      packNote: "Bund mit ~6 Stück",
    },
  }),
  mk({
    id: "zwiebel",
    name: "Zwiebel",
    namePlural: "Zwiebeln",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.25,
      packEur: 1.5,
      packNote: "2-kg-Netz",
    },
  }),
  mk({
    id: "knoblauch",
    name: "Knoblauch",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "zehe",
      eur: 0.1,
      packEur: 0.6,
      packNote: "1 Knolle",
    },
  }),
  mk({
    id: "ingwer",
    name: "Ingwer",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.8,
      packEur: 0.8,
      packNote: "Knolle",
    },
  }),
  mk({
    id: "karotte",
    name: "Karotte",
    namePlural: "Karotten",
    emoji: "🥕",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.15,
      packEur: 1.0,
      packNote: "1-kg-Beutel",
    },
  }),
  mk({
    id: "kartoffel",
    name: "Kartoffel",
    namePlural: "Kartoffeln",
    emoji: "🥔",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.15,
      packEur: 2.5,
      packNote: "2,5-kg-Sack",
    },
  }),
  mk({
    id: "spitzkohl",
    name: "Spitzkohl",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.25,
      packEur: 1.5,
      packNote: "1 Kopf",
    },
    substitutes: [
      { ingredientId: "chinakohl", text: "Chinakohl", quality: "gleichwertig" },
      { ingredientId: "weisskohl", text: "Weißkohl (fester)", quality: "okay" },
    ],
  }),
  mk({
    id: "weisskohl",
    name: "Weißkohl",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.2,
      packEur: 1.5,
      packNote: "1/2 Kopf",
    },
  }),
  mk({
    id: "chinakohl",
    name: "Chinakohl",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.25,
      packEur: 1.8,
      packNote: "1 Kopf",
    },
  }),
  mk({
    id: "pak-choi",
    name: "Pak Choi",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.9,
      packEur: 1.8,
      packNote: "2 Stück",
    },
  }),
  mk({
    id: "spinat",
    name: "Blattspinat (frisch)",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.8,
      packEur: 1.6,
      packNote: "200-g-Beutel",
    },
  }),
  mk({
    id: "gurke",
    name: "Salatgurke",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.7,
      packEur: 0.7,
      packNote: "1 Stück",
    },
  }),
  mk({
    id: "shiitake",
    name: "Shiitake (frisch)",
    namePlural: "Shiitake",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 2.0,
      packEur: 2.5,
      packNote: "Schale ~125 g",
    },
    substitutes: [
      {
        ingredientId: "champignons",
        text: "Champignons (milder)",
        quality: "okay",
      },
    ],
  }),
  mk({
    id: "champignons",
    name: "Champignons",
    namePlural: "Champignons",
    emoji: "🍄",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.8,
      packEur: 1.6,
      packNote: "250-g-Schale",
    },
  }),
  mk({
    id: "aubergine",
    name: "Aubergine",
    namePlural: "Auberginen",
    emoji: "🍆",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.9,
      packEur: 0.9,
      packNote: "1 Stück",
    },
  }),
  mk({
    id: "zucchini",
    name: "Zucchini",
    namePlural: "Zucchini",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.6,
      packEur: 0.6,
      packNote: "1 Stück",
    },
  }),
  mk({
    id: "chili-frisch",
    name: "Frische Chilischote",
    namePlural: "Chilischoten",
    emoji: "🌶️",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.3,
      packEur: 0.9,
      packNote: "kleine Schale",
    },
  }),
  mk({
    id: "apfel",
    name: "Apfel",
    namePlural: "Äpfel",
    emoji: "🍎",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.4,
      packEur: 2.5,
      packNote: "Beutel",
    },
  }),
  mk({
    id: "limette",
    name: "Limette",
    namePlural: "Limetten",
    category: "frische-zutaten",
    section: "obst-gemuese",
    perishable: true,
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.4,
      packEur: 1.2,
      packNote: "Netz",
    },
  }),

  /* ------------------------------ Tiefkühl ---------------------------- */
  mk({
    id: "edamame-tk",
    name: "Edamame (TK)",
    category: "tiefkuehl",
    section: "tiefkuehl",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.9,
      packEur: 2.5,
      packNote: "300-g-Beutel",
    },
  }),
  mk({
    id: "mais",
    name: "Mais (Dose)",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 1,
      unit: "dose",
      eur: 0.9,
      packEur: 0.9,
      packNote: "150-g-Dose",
    },
  }),
  mk({
    id: "tk-gyoza",
    name: "Gyoza (TK)",
    namePlural: "Gyoza",
    category: "tiefkuehl",
    section: "tiefkuehl",
    price: {
      amount: 1,
      unit: "stueck",
      eur: 0.18,
      packEur: 3.5,
      packNote: "Beutel ~20 Stück",
    },
  }),
  mk({
    id: "tk-erbsen",
    name: "Erbsen (TK)",
    category: "tiefkuehl",
    section: "tiefkuehl",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.35,
      packEur: 1.5,
      packNote: "450-g-Beutel",
    },
  }),

  /* --------------------- Vorratsschrank / Gewürze / Öle --------------- */
  mk({
    id: "sesam",
    name: "Sesam (geröstet)",
    category: "gewuerze-oele",
    section: "trockenwaren",
    price: {
      amount: 100,
      unit: "g",
      eur: 1.2,
      packEur: 2.0,
      packNote: "200-g-Beutel",
    },
  }),
  mk({
    id: "mehl",
    name: "Weizenmehl",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.1,
      packEur: 0.8,
      packNote: "1-kg-Packung",
    },
  }),
  mk({
    id: "speisestaerke",
    name: "Speisestärke",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.3,
      packEur: 1.0,
      packNote: "400-g-Packung",
    },
  }),
  mk({
    id: "honig",
    name: "Honig",
    emoji: "🍯",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.9,
      packEur: 4.0,
      packNote: "500-g-Glas",
    },
    substitutes: [{ text: "Zucker (etwas weniger)", quality: "gleichwertig" }],
  }),
  mk({
    id: "erdnussbutter",
    name: "Erdnussbutter",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.8,
      packEur: 3.0,
      packNote: "350-g-Glas",
    },
  }),
  mk({
    id: "sesampaste",
    name: "Sesampaste (Tahin)",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 100,
      unit: "g",
      eur: 1.2,
      packEur: 4.0,
      packNote: "Glas ~300 g",
    },
    substitutes: [
      {
        ingredientId: "erdnussbutter",
        text: "Erdnussbutter (nussiger, etwas süßer)",
        quality: "okay",
      },
    ],
  }),
  mk({
    id: "spaghetti",
    name: "Spaghetti",
    namePlural: "Spaghetti",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 100,
      unit: "g",
      eur: 0.2,
      packEur: 1.0,
      packNote: "500-g-Packung",
    },
  }),
  mk({
    id: "ketchup",
    name: "Tomatenketchup",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 100,
      unit: "ml",
      eur: 0.4,
      packEur: 1.5,
      packNote: "500-ml-Flasche",
    },
  }),
  mk({
    id: "butter",
    name: "Butter",
    category: "gewuerze-oele",
    section: "kuehlregal",
    price: {
      amount: 100,
      unit: "g",
      eur: 1.5,
      packEur: 2.4,
      packNote: "250-g-Stück",
    },
  }),
  mk({
    id: "milch",
    name: "Milch",
    emoji: "🥛",
    category: "frische-zutaten",
    section: "kuehlregal",
    perishable: true,
    price: {
      amount: 100,
      unit: "ml",
      eur: 0.12,
      packEur: 1.2,
      packNote: "1-l-Packung",
    },
  }),
  mk({
    id: "sahne",
    name: "Sahne",
    category: "frische-zutaten",
    section: "kuehlregal",
    perishable: true,
    price: {
      amount: 100,
      unit: "ml",
      eur: 0.4,
      packEur: 0.9,
      packNote: "200-ml-Becher",
    },
  }),
  mk({
    id: "sandwichbrot",
    name: "Sandwichbrot (Toast)",
    category: "vorratsschrank",
    section: "trockenwaren",
    price: {
      amount: 1,
      unit: "blatt",
      eur: 0.1,
      packEur: 1.5,
      packNote: "Packung ~14 Scheiben",
    },
  }),

  /* ------------------------------- Staples ---------------------------- */
  mk({
    id: "salz",
    name: "Salz",
    category: "gewuerze-oele",
    section: "trockenwaren",
    isStaple: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.05,
      packEur: 0.5,
      packNote: "500-g-Packung",
    },
  }),
  mk({
    id: "pfeffer",
    name: "Pfeffer",
    category: "gewuerze-oele",
    section: "trockenwaren",
    isStaple: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 1.5,
      packEur: 1.5,
      packNote: "Mühle",
    },
  }),
  mk({
    id: "zucker",
    name: "Zucker",
    category: "vorratsschrank",
    section: "trockenwaren",
    isStaple: true,
    price: {
      amount: 100,
      unit: "g",
      eur: 0.1,
      packEur: 1.0,
      packNote: "1-kg-Packung",
    },
  }),
  mk({
    id: "oel-neutral",
    name: "Neutrales Öl",
    category: "gewuerze-oele",
    section: "trockenwaren",
    isStaple: true,
    price: {
      amount: 100,
      unit: "ml",
      eur: 0.2,
      packEur: 3.0,
      packNote: "1-l-Flasche",
    },
  }),
  mk({
    id: "wasser",
    name: "Wasser",
    category: "vorratsschrank",
    section: "sonstiges",
    isStaple: true,
    price: { amount: 100, unit: "ml", eur: 0.0 },
  }),
];
